### ISSUE TITLE
coh3 files - array dimensions exceeded supported range

### ISSUE THREAD

**Issue by rempAut** [Janne252/essence-archive-viewer#3]
Hey there,
I tried to open COH3 file  (coh3\anvil\archives\UI.sga) but got an error message, loosely translated as "array dimensions exceeded supported range".
I get this error message for every other *.sga file as well. Do you have any ideas what can be causing this issue please?

**Comment by Janne252** [comment]
I've noticed similar issues. I think the best solution right now is to see what mod tools Age of Empires IV offers. If there's a publicly accessible build of CoH3, I'll certainly update this tool with the latest library.

**Comment by rempAut** [comment]
Oh that's unfortunate. I tried using AoE4 tools, but with no result. Anyways thanks for the great tool.
