### ISSUE TITLE
Can't extract any CoH3 .sga contents, all fail with "Error reading data for file ..."

### ISSUE THREAD

**Issue by Chematronix** [Janne252/essence-archive-viewer#4]
Hi again,

I get the above error with the latest viewer with all of my mod's sgas (subscriptions from Steam).  Is it broken for everyone?

Actually, I just wanna look into CheatCommands, is the source available somewhere?  I'm interested in adding a unit save/load feature, so you can spawn a bunch of them at once, in their desired positions.  Eventually I'd like to make training/challenge scenarios.  I'm new to modding CoH, tho a codemonkey by trade, so if you could at least point me into the right direction, I'd appreciate it.  Thanks!

**Comment by Janne252** [comment]
Hey, this patched tool isn't needed anymore as both AoE4 and CoH3 are shipped with Essence Editor which can be used to extract the games' .sga archives. Add me on Discord or Steam if you want to chat about CheatCommands mod.

**Comment by Chematronix** [comment]
Oh, that explains that then.  I'll ring you up soon, cheers!

**Comment by Chematronix** [comment]
Oh man, here I was going blind with old CoH2 Scardocs, and just found you have updated ones in your coh3-scar-types (which papa Google has entirely failed to oogle).

Spawning units was easy enough, but haven't been able to get `Rule_AddSGroupEvent(rule, self.groupID, GE_SquadKilled)` nor `Event_Death(log, self.groupID, ANY_MEMBER, true, false, { "Dead soldier for Player" .. self.idx })` to work, so I added you.  Are you active in any public forum?

Better, could throw the Scardocs in a repo and document them in the Wiki, what do you think?
